db:
  image: "postgres:13.20"
  host: "db"
  port: 5432
  database: "backend"
  user: "backend_user"
  password: "backend_user_pwd"
  volumeSize: "1Gi"
 
backend:
  image: "registry.example.com/backend"
  tag: "latest"
  port: 8180
  prefectApiUrl: "https://prefect.ons.vita.local/api"
  stageStatusQueryTimeout: 1
  numWorkers: 5
  host: "backend"
 
frontend:
  image: "registry.example.com/frontend"
  tag: "latest"
  port: 80

ingress:
  frontendHost: "observer.ons.vita.local"
  backendHost: "api-observer.ons.vita.local"
  className: "nginx"
