services:
  db:
    image: postgres:13.20
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${OBSERVER_DB_USER}
      - POSTGRES_PASSWORD=${OBSERVER_DB_PWD}
      - POSTGRES_DB=${OBSERVER_DB_DATABASE}
      - POSTGRES_PORT=${OBSERVER_DB_PORT}
      - POSTGRES_HOST=${OBSERVER_DB_HOST}
    ports:
      - "${OBSERVER_DB_PORT}:${OBSERVER_DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app
  
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "${OBSERVER_APP_PORT}:${OBSERVER_APP_PORT}"
    depends_on:
      - db
    networks:
      - app
  
  frontend:
    env_file:
      - .env
    build: 
      context: ./frontend
      args:
        - "BACKEND_API_HOST=http://${OBSERVER_APP_HOST}:${OBSERVER_APP_PORT}"
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app

volumes:
  db_data:

networks:
  app:
    driver: bridge
