apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullnameOverride | default .Release.Name }}-backend
  namespace: observer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.fullnameOverride | default .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.fullnameOverride | default .Release.Name }}-backend
    spec:
      containers:
        - name: observer-backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          env:
            - name: OBSERVER_DB_HOST
              value: "{{ .Values.db.host }}"
            - name: OBSERVER_DB_PORT
              value: "{{ .Values.db.port }}"
            - name: OBSERVER_DB_DATABASE
              value: "{{ .Values.db.database }}"
            - name: OBSERVER_DB_USER
              value: "{{ .Values.db.user }}"
            - name: OBSERVER_DB_PWD
              value: "{{ .Values.db.password }}"
            - name: OBSERVER_APP_PORT
              value: "{{ .Values.backend.port }}"
            - name: OBSERVER_APP_PREFECTAPIURL
              value: "{{ .Values.backend.prefectApiUrl }}"
            - name: OBSERVER_APP_STAGESTATUSQUERYTIMEOUT
              value: "{{ .Values.backend.stageStatusQueryTimeout }}"
            - name: OBSERVER_APP_NUMWORKERS
              value: "{{ .Values.backend.numWorkers }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
