apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.fullnameOverride | default .Release.Name }}-ingress
  namespace: observer
  labels:
    app: {{ .Values.fullnameOverride | default .Release.Name }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.backendHost }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.fullnameOverride | default .Release.Name }}-backend
                port:
                  number: {{ .Values.backend.port }}
    - host: {{ .Values.ingress.frontendHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.fullnameOverride | default .Release.Name }}-frontend
                port:
                  number: {{ .Values.frontend.port }}
 
 