apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride | default .Release.Name }}-backend
  namespace: observer
spec:
  selector:
    app: {{ .Values.fullnameOverride | default .Release.Name }}-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
