/* tslint:disable */
/* eslint-disable */
/**
 * OBSERVER backend
 * This is a backend for OBSERVER app.
 *
 * The version of the OpenAPI document: 1.2
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

